name: CI

on:
  push:
  pull_request: ~

jobs:
  shared-ci:
    uses: zigpy/workflows/.github/workflows/ci.yml@puddly/pre-commit
    with:
      CODE_FOLDER: zigpy
      CACHE_VERSION: 2
      PYTHON_VERSION_DEFAULT: 3.9.15
      PRE_COMMIT_CACHE_PATH:  ~/.cache/pre-commit
      MINIMUM_COVERAGE_PERCENTAGE: 99
